### ISSUE TITLE
@lens-protocol/client - XMLHttpRequest error on Cloudflare functions (Remix loader)

### ISSUE THREAD

**Issue by korzewski** [lens-protocol/lens-sdk#285]
Hey everyone!
Today I started to play around with Lens API's.
GraphQL queries works great, although I wanted to get advantage of types by using this package **@lens-protocol/client**. 

Unfortunately it seems to not work at Cloudflare functions:
_ReferenceError: XMLHttpRequest is not defined_
I'm using Remix loader here^^

**To Reproduce**
- Create new Remix app **npx create-remix@latest**
- Deployment configuration **Cloudflare Pages**
- At any route create loader function and run any query
 ```
const result = await lensClient.explore.profiles({
    sortCriteria: ProfileSortCriteria.CreatedOn,
});
 ```
- I got an error `ReferenceError: XMLHttpRequest is not defined` - As Cloudflare functions supports only Fetch API's.

Worth to mention same code used at frontend **useEffect()** works as expected.

**Expected behaviuor**
Lens client would work at Remix Cloudflare Pages without errors

**Version of the packages you are using**
- "@lens-protocol/client": "^0.3.0",
- "@remix-run/cloudflare": "^1.15.0",
- "@remix-run/cloudflare-pages": "^1.15.0",

**Additional context**
Are there any plans to switch over to Fetch API? Or some other known workaround for it?

Thanks

**Comment by desfero** [comment]
Thanks for reporting the issue @korzewski.
It seems under the hood lib that we use is using by default XMLHTTPRequest (quite weird to still use it given how broadly available across ecosystems the `fetch API` is 🤔 ).
see: https://github.com/jasonkuhrt/graphql-request/issues/399

Anyway, the fix is very simple, will try to talk with the team to push it ASAP.
