### ISSUE TITLE
Issue with Wagmi and Ethers 

### ISSUE THREAD

**Issue by swarajbachu** [lens-protocol/lens-sdk#335]
**Describe the bug**
Issue with Wagmi
![WhatsApp Image 2023-05-14 at 9 13 59 PM](https://github.com/lens-protocol/lens-sdk/assets/97094800/93de85ce-38af-4b76-8fab-f7a8e77f86da)

**To Reproduce**
Basic Sdk setup, nextjs 13.4, page directory 

**Expected behaviuor**
There is problem with wagmi and ethers, wagmi supports ethers version 5.7.2, but when installed according to documentation it installs recent version and may cause problems.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App
- [ ] React Native 

**Additional context**
I know wagmi would be trying to get the fix, but we should also give good experience to our users from our side, as the sdk was released just 2 days ago, we can may be improve documentation ( for time being ) or find some possible fix

** How I fixed it **
I just migrated my ethers module back to 5.7.2 and its up and running

**Comment by cesarenaldi** [comment]
Good point. Ultimately the package manager should have warned you with a mismatch between installing `ethers@6.x` vs. the requires `ethers@5.7.x` but I can totally relate with providing a good DX.

I updated the docs to use:
```
yarn add @lens-protocol/react-web ethers@legacy-v5
```

Longer term, we are going to look into supporting wagmi 1.0 very soon, so things might change in this space given wagmi moving to use viem instead of ethers.

**Comment by swarajbachu** [comment]
Yeah ! thank you Shall I close the issue ?
