### ISSUE TITLE
Allow usefeed access without walletlogin authentication.

### ISSUE THREAD

**Issue by chazzaoui** [lens-protocol/lens-sdk#410]
**Is your feature request related to a problem? Please describe.**
Currently building [https://www.lensclubs.xyz/](url) where we allow communities, dao's, and companies to collaborate under one lens handle. The way we handle this is by using a smart-contract wallet where we talk directly to the lens contract.

This also means we can't authenticate, since we don't have a private key, and therefore can't use the usefeed hook.

**Describe the solution you'd like**
A way for us to get the feed of a certain profileID without having to authenticate. Or allowing us to be able to authenticate once as lens-clubs and allow the smart contracts wallets to retrieve feed without being limited in the API.

Would be great if we can find a solution for this, The lens SDK has been nothing but great so far, but this is a major blocker for us at the moment.

Thanks for taking the time!

**Comment by desfero** [comment]
Hey @chazzaoui,
making the feed accessible without the authenticated profile is not an option for now due to the extensive caching on the API side that's using authenticated wallet address as a cache key.

Let's try to explore the second option to authenticate the user. 
Who is storing the private key of that wallet that holds that collaborative lens handle?

**Comment by cesarenaldi** [comment]
Closing this as getting stale. Feel free to reopen.
