### ISSUE TITLE
useCreateMirror returns _ref undefined error

### ISSUE THREAD

**Issue by jsonpreet** [lens-protocol/lens-sdk#423]
**Describe the bug**
`const { execute: create, isPending, error } = useCreateMirror();`

Hi, I use the above code in my file and I got _ref undefined error, when I removed this line everything working fine.

![Screenshot 2023-07-17 123116](https://github.com/lens-protocol/lens-sdk/assets/26606638/d13cbc2b-0e57-4734-938d-bf6362ec839d)

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
1.2.1

**Comment by cesarenaldi** [comment]
The issue is because your are not passing the arguments the hook expects.

Reference doc: https://lens-protocol.github.io/lens-sdk/functions/_lens_protocol_react_web.useCreateMirror.html

Working example: https://github.com/lens-protocol/lens-sdk/blob/main/examples/web-wagmi/src/publications/UseCreateMirror.tsx#L26

**Comment by cesarenaldi** [comment]
> okay thank you, it's not mentioned in docs.lens.xyz

Ah thank you for pointing this out. I'll fix it now.

A note on the docs I hope you can find useful.

In order to keep the documents easier to maintain and keep up to date we are rethinking the `docs.lens.xyz` to become more of a collection of guides. See [create your first post](https://docs.lens.xyz/docs/create-first-post) format for example.

What used the be the older format (like in the case of https://docs.lens.xyz/docs/use-create-mirror) is going to be autogenerated from TSDoc (i.e. the [reference docs](https://lens-protocol.github.io/lens-sdk/index.html)).

Reference docs over time will be integrated with also snippets of code you can see from the docs and from your IDE.
An example: https://lens-protocol.github.io/lens-sdk/functions/_lens_protocol_react_web.useCreatePost.html

The `useCreateMirror` is just not migrated to the new format yet.
