### ISSUE TITLE
Regression in latest version of the SDK 2.0.0-alpha.29 when creating a publication

### ISSUE THREAD

**Issue by pradel** [lens-protocol/lens-sdk#824]
**Describe the bug**

After upgrading my app from:

```
- "@lens-protocol/client": "2.0.0-alpha.27",
+ "@lens-protocol/client": "2.0.0-alpha.29",

- "@lens-protocol/react-web": "2.0.0-alpha.27",
+ "@lens-protocol/react-web": "2.0.0-alpha.29",
   
- "@lens-protocol/wagmi": "3.0.0-alpha.24",
+ "@lens-protocol/wagmi": "3.0.0-alpha.25",
```

Publishing new on-chain posts stopped working, and I am getting an `InvariantError: Publication for 0x3ffec8aa79cbc1f29fe01ee53b2eb0b93fec2ac90c1d26e0622a73b13f9531f6 not found` error.
I get this error consistently, the post is published on-chain but the SDK throws this error breaking the app flow.

The error seems to happen when I call `result.value.waitForCompletion()` for the following code:

```ts
const { execute: createPost, loading: loadingCreatePost } = useCreatePost();

const result = await createPost({
            metadata: arweaveUrl,
            actions: [action],
          });

// Error seems to be thrown after this call
const completionResult = await result.value.waitForCompletion();
```

Note: If I downgrade the deps to the previous version I was using the flow works just fine with the same code and I can publish without issues.

**To Reproduce**

Try to publish an on-chain post with an action with the latest version of the SDK

**Expected behavior**

The upgrade should not have any regression.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App
- [ ] React Native 

**Version of the packages you are using**

```
"@lens-protocol/client": "2.0.0-alpha.29",
"@lens-protocol/react-web": "2.0.0-alpha.29",
"@lens-protocol/wagmi": "3.0.0-alpha.25",
```

**Comment by cesarenaldi** [comment]
hey @pradel thank you for the detailed bug report. I tried this, this morning but without success. Was this against Testnet or Mainnet?

Can you please try with `useCreateComment` on the SDK playground here: https://lens-sdk-example-web-wagmi.vercel.app/publications/useCreateComment

I am suggesting `useCreateComment` instead of `useCreatePost` simply because the playground setup would attempt a Momoka publication with `useCreatePost` example.

**Comment by pradel** [comment]
The issue is happening on tesnet (my app isn't running on mainnet so don't know if it's a testnet specific issue). It doesn't seem to be related to the Lens API as downgrading the deps is working.

> Can you please try with useCreateComment on the SDK playground here: [lens-sdk-example-web-wagmi.vercel.app/publications/useCreateComment](https://lens-sdk-example-web-wagmi.vercel.app/publications/useCreateComment)

Just tried and it's working fine.

> I am suggesting useCreateComment instead of useCreatePost simply because the playground setup would attempt a Momoka publication with useCreatePost example.

Would be nice to have the option to select between momoka and on chain when creating a post in the playground (maybe a simple radio button?) :)

**Comment by pradel** [comment]
Btw I just retried this morning just in case and still facing the same issue. I can share a link of my testnet app if you want to test (not sure if it's useful or not without the source code). If it can help feel free to DM me on discord so I can send the link there.

**Comment by cesarenaldi** [comment]
For posterity, this turns out to be an issue with Apollo Client 3.9.x and the way that cache is updated/used on new data.

There's several open issue on the Apollo Client GH related to anomalies in the way data is returned/not-returned in some circumstances.

We didn't narrow it down on which on exactly affects the Lens SDK. For now we recommend to stay with Apollo Client 3.8.x.

See PR: https://github.com/lens-protocol/lens-sdk/pull/825

Thank you @pradel for the help.

**Comment by pradel** [comment]
@cesarenaldi just tried with apollo 3.9.5 and can confirm the error is gone, you can remove the apollo 3.8.x requirement and close the issue if you want :)

**Comment by cesarenaldi** [comment]
ah, thank you @pradel this saves me time to investigate.

**Comment by cesarenaldi** [comment]
Change in this PR: https://github.com/lens-protocol/lens-sdk/pull/857

**Comment by krzysu** [comment]
the version of the sdk with apollo 3.9.5 was just released. I'm closing this issue.
